remote_theme: jekyll/minima@c6e74bb
plugins:
- jekyll-remote-theme 
title: Salesforce DeFacto
description: Practical applications of Salesforce features and capabilities
author: "Taha Basri"
email: "tahabsri@gmail.com"
repository: https://github.com/tahabasri/Salesforce-DeFacto
minima:
  skin: auto # switch light/dark with system settings.
  social_links:
    - title: Salesforce Defacto repository at GitHub
      icon: github
      url: "https://salesforce-defacto.tahabasri.com"
    - title: Taha Basri - Portfolio
      icon: fa-hand-peace
      url: "https://tahabasri.com/"
    - title: Taha Basri - LinkedIn
      icon: fa-linkedin
      url: "https://www.linkedin.com/in/tahabasri/"
